# Generated by Django 2.1.15 on 2022-02-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCare', '0003_tbluserdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='MHeight',
            fields=[
                ('heightid', models.CharField(db_column='heightID', max_length=36, primary_key=True, serialize=False)),
                ('height_value', models.FloatField()),
                ('addedon', models.DateTimeField()),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField()),
                ('version', models.TextField()),
            ],
            options={
                'db_table': 'm_height',
                'managed': False,
            },
        ),
    ]
