# Generated by Django 2.1.15 on 2022-02-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCare', '0004_mheight'),
    ]

    operations = [
        migrations.CreateModel(
            name='MBloodgroup',
            fields=[
                ('bloodgroupid', models.CharField(db_column='bloodgroupID', max_length=36, primary_key=True, serialize=False)),
                ('shortcode', models.CharField(max_length=3)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('addedon', models.DateTimeField()),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField()),
                ('version', models.TextField()),
            ],
            options={
                'db_table': 'm_bloodgroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MBmi',
            fields=[
                ('bmiid', models.CharField(db_column='bmiID', max_length=36, primary_key=True, serialize=False)),
                ('bmi', models.FloatField()),
                ('addedon', models.DateTimeField()),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField()),
                ('version', models.TextField()),
            ],
            options={
                'db_table': 'm_bmi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MGender',
            fields=[
                ('genderid', models.CharField(db_column='genderID', max_length=36, primary_key=True, serialize=False)),
                ('shortcode', models.CharField(max_length=1)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('addedon', models.DateTimeField()),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField()),
                ('version', models.TextField()),
            ],
            options={
                'db_table': 'm_gender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MWeight',
            fields=[
                ('weightid', models.CharField(db_column='weightID', max_length=36, primary_key=True, serialize=False)),
                ('weight_value', models.FloatField()),
                ('addedon', models.DateTimeField()),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField()),
                ('version', models.TextField()),
            ],
            options={
                'db_table': 'm_weight',
                'managed': False,
            },
        ),
    ]
