# Generated by Django 2.1.15 on 2022-02-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCare', '0005_mbloodgroup_mbmi_mgender_mweight'),
    ]

    operations = [
        migrations.CreateModel(
            name='MEntityDetail',
            fields=[
                ('entityid', models.CharField(db_column='entityID', max_length=36, primary_key=True, serialize=False)),
                ('entityname', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'm_entity_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MLocationDetail',
            fields=[
                ('locationid', models.CharField(db_column='locationID', max_length=36, primary_key=True, serialize=False)),
                ('location_pincode', models.IntegerField()),
                ('location_longitude', models.FloatField()),
                ('location_latitude', models.FloatField()),
                ('location_name', models.CharField(max_length=255)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'm_location_detail',
                'managed': False,
            },
        ),
    ]
