# Generated by Django 2.1.15 on 2022-02-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCare', '0006_mentitydetail_mlocationdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='MEntitySpeciality',
            fields=[
                ('entity_speciality_id', models.CharField(db_column='entity_speciality_ID', max_length=36, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'm_entity_speciality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MSpeciality',
            fields=[
                ('specialityid', models.CharField(db_column='specialityID', max_length=36, primary_key=True, serialize=False)),
                ('speciality', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'm_speciality',
                'managed': False,
            },
        ),
    ]
